### ISSUE TITLE
Bump the version to v2.0.0

### ISSUE THREAD

**Issue by xel1045** [eXolnet/laravel-status#1]
Since this package already exists from the old `exolnet/laravel-module`, we need to bump the version to 2.0.0

**Comment by martinblanchette** [comment]
@xel1045 the package version is updated. I think you need to update [Packagist](https://packagist.org/packages/eXolnet/laravel-status) in order to have an updated flag version in the [README.md](https://github.com/eXolnet/laravel-status/blob/master/README.md) 👇

![image](https://user-images.githubusercontent.com/157875/49962859-6678ee00-fee4-11e8-8ae3-846ee5822ab1.png)

**Comment by xel1045** [comment]
@martinblanchette Did you have the permissions to do that or you don't know how to do it?

**Comment by martinblanchette** [comment]
@xel1045 I know pretty much what to do, the problem is that I have limited permission on the repository.
